name: ci

on: [push, pull_request]

jobs:
  # ci-macos:
  #   runs-on: macos-latest

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       php: [7.4]
  #       swoole: [4.6]

  #   env:
  #     MYSQL_SERVER_PASSWORD: ""

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: install db
  #       run: |
  #         brew install mysql redis
  #         mysqld --initialize-insecure
  #         brew services start mysql
  #         brew services start redis

  #     - name: install php
  #       run: .github/macos/install-php7.4-mac.sh

  #     - name: install swoole
  #       run: sudo .github/macos/install-swoole4.6.sh

  #     - name: prepare
  #       run: |
  #         composer update
  #         mysql -e 'CREATE DATABASE IF NOT EXISTS db_imi_test;'
  #         tests/db/install-db.sh

  #     - name: test
  #       run: |
  #         composer test-all

  #     - name: print logs
  #       if: failure()
  #       run: php .github/print-logs.php

  ci-php:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        swoole: [4.6-php7.4, 4.6-php8.0]
        # mysql: [5.7, 8.0]
        mysql: [8.0]

    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}
      MYSQL_DOCKER_VERSION: ${{ matrix.mysql }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          ./.github/prepare-test.sh swoole

      - name: test
        run: docker exec swoole composer test-all

      - name: print logs
        if: failure()
        run: docker exec swoole php .github/print-logs.php
